# Public Service
apiVersion: v1
kind: Service
metadata:
  name: httpbin-public
  labels:
    app: httpbin        
spec:
  selector:
    app: httpbin        
  ports:
    - port: 80          # Traffic -> Service (port 80) -> Pod (target_port 80)
      targetPort: 80
      protocol: TCP

---

# Internal Service
apiVersion: v1
kind: Service
metadata:
  name: httpbin-internal
  labels:
    app: httpbin        
    access: internal
spec:
  selector:
    app: httpbin       
  ports:
    - port: 80          # Traffic -> Service (port 80) -> Pod (target_port 80)
      targetPort: 80
      protocol: TCP